service: default
runtime: python310 
entrypoint: gunicorn -b :$PORT main:app  

env_variables:
  SECRET_KEY: "86c00f1688fb3d884aae8cfc602f2353"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
